language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
    - phpenv rehash

install:
    - composer self-update
    - composer install
    - composer require cakephp/cakephp-codesniffer:dev-master

script:
  - phpunit

notifications:
  email: andre@orainteractive.com